---
- hosts: ip-172-31-54-232.ec2.internal 
  remote_user: ec2-user

  tasks:
  - name: clone repository
    git: repo=https://github.com/GeorgeKopf/DevOpsProject.git
         dest=/home/ec2-user/DevOpsProject
         accept_hostkey=yes
         force=yes
    register: gitclone
  
  - name: copy
    command: cp /home/ec2-user/DevOpsProject/index.html /usr/share/tomcat/webapps/ROOT/index.html
    become: yes
    become_user: root
    when: gitclone.changed

  - uri: url=https://52.201.234.9:8443/index.html return_content=yes validate_certs=no
    register: webpage

  - action: fail
    when: "'Hello Anne!' not in webpage.content"
